### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by snobjorn** [mhfowler/AltTextGpt#2]
Settings:
Batch set to 1 (or 10)

Error message:
Breaking news… Fatal feil: Uncaught TypeError: Exception::__construct(): Argument #1 ($message) must be of type string, array given in site/modules/AltTextGpt/AltTextGpt.module.php:242

```
#0 site/modules/AltTextGpt/AltTextGpt.module.php(242): Exception->__construct(Array)
#1 site/modules/AltTextGpt/AltTextGpt.module.php(311): AltTextGpt->generateAltText('sk-proj-xxx...', 'gpt-4o', 'Generate alt te...', '//site/assets/f...')
#2 site/modules/AltTextGpt/AltTextGpt.module.php(129): AltTextGpt->processForm(Object(InputfieldForm))
#3 site/modules/AltTextGpt/AltTextGpt.module.php(52): AltTextGpt->___executeForm()
#4 wire/core/Wire.php (413): AltTextGpt->___execute()
#5 wire/core/WireHooks.php (968): Wire->_callMethod('___execute', Array)
#6 wire/core/Wire.php (484): WireHooks->runHooks(Object(AltTextGpt), 'execute', Array)
#7 wire/core/ProcessController.php (361): Wire->__call('execute', Array)
#8 wire/core/Wire.php (413): ProcessController->___execute()
#9 wire/core/WireHooks.php (968): Wire->_callMethod('___execute', Array)
#10 wire/core/Wire.php (484): WireHooks->runHooks(Object(ProcessController), 'execute', Array)
#11 wire/core/admin.php (160): Wire->__call('execute', Array)
#12 wire/modules/AdminTheme/AdminThemeUikit/controller.php (15): require('/Users/xxx...')
#13 site/templates/admin.php (15): require('/Users/xxx...')
#14 wire/core/TemplateFile.php (328): require('/Users/xxx...')
#15 wire/core/Wire.php (413): TemplateFile->___render()
#16 wire/core/WireHooks.php (968): Wire->_callMethod('___render', Array)
#17 wire/core/Wire.php (484): WireHooks->runHooks(Object(TemplateFile), 'render', Array)
#18 wire/modules/PageRender.module (574): Wire->__call('render', Array)
#19 wire/core/Wire.php (416): PageRender->___renderPage(Object(HookEvent))
#20 wire/core/WireHooks.php (968): Wire->_callMethod('___renderPage', Array)
#21 wire/core/Wire.php (484): WireHooks->runHooks(Object(PageRender), 'renderPage', Array)
#22 wire/core/WireHooks.php (1094): Wire->__call('renderPage', Array)
#23 wire/core/Wire.php (484): WireHooks->runHooks(Object(Page), 'render', Array)
#24 wire/modules/Process/ProcessPageView.module (184): Wire->__call('render', Array)
#25 wire/modules/Process/ProcessPageView.module (114): ProcessPageView->renderPage(Object(Page), Object(PagesRequest))
#26 wire/core/Wire.php (416): ProcessPageView->___execute(true)
#27 wire/core/WireHooks.php (968): Wire->_callMethod('___execute', Array)
#28 wire/core/Wire.php (484): WireHooks->runHooks(Object(ProcessPageView), 'execute', Array)
#29 index.php (55): Wire->__call('execute', Array)
#30 {main}
thrown (linje 242 i site/modules/AltTextGpt/AltTextGpt.module.php)
```

**Comment by mhfowler** [comment]
hmm I've just tested the module out again using the code directly from github on a fresh install of processwire using the "beginners minimal" profile, and it was working.

I just merged a pull request that fixed an issue with configuring the Base URL for images, but that doesn't look related to this

Its hard for me to tell from this error message what the issue could be

**Comment by snobjorn** [comment]
Looks like it was related to my local setup, where I first tested the module.

When the base URL is just /, the error shows.

When setting the `$baseUrl` to the domain for the live version of the site, it works.
